[tox]
minversion = 4.28.0
envlist = py3,pep8

[testenv]
description =
  Run unit tests.
constraints =
  {env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}
dependency_groups =
  test
commands =
  stestr run --slowest {posargs}

[testenv:venv]
commands = {posargs}

[testenv:docs]
allowlist_externals =
  rm
dependency_groups =
  doc
commands =
  rm -fr doc/build
  sphinx-build -W --keep-going -b html doc/source doc/build/html

[testenv:releasenotes]
allowlist_externals =
  rm
dependency_groups =
  doc
commands =
  rm -rf releasenotes/build
  sphinx-build -W --keep-going -b html releasenotes/source releasenotes/build/html

[testenv:pep8]
description =
  Run style checks.
skip_install = true
constraints =
deps =
  pre-commit
commands =
  pre-commit run -a

[flake8]
# We only enable the hacking (H) checks
select = H
# H301 Black will put commas after imports that can't fit on one line
# H404 Docstrings don't always start with a newline
# H405 Multiline docstrings are okay
ignore = H301,H403,H404,H405
show-source = True

[hacking]
import_exceptions = oslo_web._i18n
